### PR TITLE
Ported cpu_monitor to ROS2

### PR DESCRIPTION
**Pull request by RichardvdK**
I attempted to port the cpu_monitor to ROS2. The module allows users to monitor the CPU usage of their system in real time. It publishes the usage percentage in a diagnostic message.

- I kept the ros arguments warning_percentage and window.
- Added 3 unit tests 

Question to you guys; is the test test_updater() overkill in this context or does it add value?

### CODE REVIEW

**Comment by MCFurry** [comment]
LGTM! I think we can open this PR to the original repo indeed.

The ROS1 node also had tests, so I think this is good!

**Review by MCFurry — APPROVED** [review]

**Comment by Timple** [comment]
Flake 8 issue. But other than that, just forward to the ros repo.

**Comment by Rayman** [comment]
Yes LGTM, only a few flake8 errors remaining

**Review by mbharatheesha — APPROVED** [review]
LGTM

**Comment by Timple** [comment]
This should not have been merged. This PR should have been redicted to github/ros/diagnostics.

**Pull request merged**
